version: "3.1"
services:
    postgres:
        image: mdillon/postgis:9.6-alpine
        environment:
            POSTGRES_PASSWORD: 1234
            POSTGRES_USER: upcmgr
            POSTGRES_DB: upc
        volumes: 
            - "/scratch/sakins/upc:/var/lib/postgresql/data"
        ports:
            - "9010:5432"

    admin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: admin
          PGADMIN_DEFAULT_PASSWORD: 1234
        volumes:
          - ./pgadmin-config:/var/lib/pgadmin
        ports:
            - "9011:80"
