version: "3.1"
services:
    postgres:
        image: mdillon/postgis:9.6-alpine
        environment:
            POSTGRES_PASSWORD: 1234
            POSTGRES_USER: upcmgr
            POSTGRES_DB: upc
        volumes: 
            - "/scratch/pds_services/database:/var/lib/postgresql/data"
        ports:
            - "9010:5432"

    admin:
        image: jlaura/pgadmin4:0.2
        ports:
            - "9011:5050"