version: '2.1'
services:
    redis:
        image: 'redis:latest'
        # command: redis-server --requirepass redispass

        ports:
            - "6379:6379"

    postgres:
        image: mdillon/postgis:9.6-alpine
        environment:
            # No password
            POSTGRES_USER: postgres
        volumes:
            - "${UPC_DATABASE_PATH}:/var/lib/postgresql/data"
        ports:
            - "5432:5432"

    admin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: admin
          PGADMIN_DEFAULT_PASSWORD: 1234
        volumes:
          - ./pgadmin-config:/var/lib/pgadmin
        ports:
            - "9011:80"
