log_format = '%(asctime)s - %(name)s - %(levelname)s, %(message)s'

jobconfig = {'di': {'logger': 'DIprocess_HPCjob',
                    'handle': '/usgs/cdev/PDS/logs/DI.log',
                    'info': 'Starting DI Process HPC Job Submission',
                    'name': 'PDS_DIprocess',
                    'stdout': '/usgs/cdev/PDS/output/DIprocess_%A_%a.out',
                    'stderr': '/usgs/cdev/PDS/output/DIprocess_%A_%a.err',
                    'memory': '8192',
                    'wallclock': '240:00:00',
                    'partition': 'pds',
                    'cmd': '/usgs/cdev/PDS/bin/DIprocess.py',
                    'SBfile': '/usgs/cdev/PDS/output/DIhpc@date@.sbatch'},
             'upc': {'logger': 'UPCprocess_HPCjob',
                    'handle': '/usgs/cdev/PDS/logs/UPC.log',
                    'info': 'Starting UPC Process HPC Job Submission',
                    'name': 'PDS_UPCprocess',
                    'stdout': '/usgs/cdev/PDS/output/UPCprocess_%A_%a.out',
                    'stderr': '/usgs/cdev/PDS/output/UPCprocess_%A_%a.err',
                    'memory': '8192',
                    'wallclock': '20:00:00',
                    'partition': 'pds',
                    'cmd': '/usgs/cdev/PDS/bin/UPC_process.py',
                    'SBfile': '/usgs/cdev/PDS/output/UPChpc@date@.sbatch'},
             'checksumupdate': {'logger': 'ChecksumUpdateprocess_HPCjob',
                                'handle': '/usgs/cdev/PDS/logs/DI.log',
                                'info': 'Starting Checksum Update Process HPC Job Submission',
                                'name': 'PDS_CSUprocess',
                                'stdout': '/usgs/cdev/PDS/output/CSUprocess_%A_%a.out',
                                'stderr': '/usgs/cdev/PDS/output/CSUprocess_%A_%a.err',
                                'memory': '8192',
                                'wallclock': '20:00:00',
                                'partition': 'pds',
                                'cmd': '/usgs/cdev/PDS/bin/ChecksumUpdateProcess.py',
                                'SBfile': '/usgs/cdev/PDS/output/CSUhpc@date@.sbatch'},
             'ingest': {'logger': 'INGESTprocess_HPCjob',
                        'handle': '/usgs/cdev/PDS/logs/Ingest.log',
                        'info': 'Starting Ingest Process HPC Job Submission',
                        'name': 'PDS_Ingestprocess',
                        'stdout': '/usgs/cdev/PDS/output/Ingestprocess_%A_%a.out',
                        'stderr': '/usgs/cdev/PDS/output/Ingestprocess_%A_%a.err',
                        'memory': '8192',
                        'wallclock': '240:00:00',
                        'partition': 'pds',
                        'cmd': '/usgs/cdev/PDS/bin/IngestProcess.py',
                        'SBfile': '/usgs/cdev/PDS/output/Ingesthpc@date@.sbatch'},
             'thumbnail': {'logger': 'Thumbnailprocess_HPCjob',
                           'handle': '/usgs/cdev/PDS/logs/Process.log',
                            'info': 'Starting Thumbnail Process HPC Job Submission',
                            'name': 'PDS_Thumbnailprocess',
                            'stdout': '/usgs/cdev/PDS/output/Thumbnailprocess_%A_%a.out',
                            'stderr': '/usgs/cdev/PDS/output/Thumbnailprocess_%A_%a.err',
                            'memory': '8192',
                            'wallclock': '20:00:00',
                            'partition': 'pds',
                            'cmd': '/usgs/cdev/PDS/bin/thumbnail_process.py',
                            'SBfile': '/usgs/cdev/PDS/output/Thpc@date@.sbatch'},
             'browse': {'logger': 'Browseprocess_HPCjob',
                        'handle': '/usgs/cdev/PDS/logs/Process.log',
                        'info': 'Starting Browse Process HPC Job Submission',
                        'name': 'PDS_Browseprocess',
                        'stdout': '/usgs/cdev/PDS/output/Browseprocess_%A_%a.out',
                        'stderr': '/usgs/cdev/PDS/output/Browseprocess_%A_%a.err',
                        'memory': '8192',
                        'wallclock': '20:00:00',
                        'partition': 'pds',
                        'cmd': '/usgs/cdev/PDS/bin/browse_process.py',
                        'SBfile': '/usgs/cdev/PDS/output/Bhpc@date@.sbatch'},
             'projectionBrowse': {'logger': 'ProjectionBrowseProcess_HPCjob',
                                  'handle': '/usgs/cdev/PDS/logs/Process.log',
                                  'info': 'Starting Projection Browse Process HPC Job Submission',
                                  'name': 'PDS_ProjBrowseprocess',
                                  'stdout': '/usgs/cdev/PDS/output/ProjBrowseprocess_%A_%a.out',
                                  'stderr': '/usgs/cdev/PDS/output/ProjBrowseprocess_%A_%a.err',
                                  'memory': '8192',
                                  'wallclock': '20:00:00',
                                  'partition': 'pds',
                                  'cmd': '/usgs/cdev/PDS/bin/projectionbrowse_process.py',
                                  'SBfile': '/usgs/cdev/PDS/output/Phpc@date@.sbatch'}
             }
